1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [76]:
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt

N = 2000
mu1, sigma1 = 0,1
x1 = np.random.normal(mu1, sigma1, N)
mu2, sigma2 = 0,3
x2 = x1 + np.random.normal(mu2, sigma2, N)
x3 = 2*x1 + x2
X = np.c_[x1,x2,x3].T
averages = np.mean(X, axis = 1).reshape(3,1)
#print(averages)
X -= averages
#print(X)


l, V = la.eig(np.cov(X))
print(l)
print(V)

U, spectrum, Vt = np.linalg.svd(X)
#print(U, U.shape)
#print(spectrum, spectrum.shape)
#print(Vt, Vt.shape)
l_svd = spectrum**2/(N-1)
V_svd = U

print(l_svd)
print(V_svd)

[ 2.69040970e+01+0.j -2.11443971e-15+0.j  2.02683591e+00+0.j]
[[-0.11204534 -0.81649658  0.56637371]
 [-0.58161795 -0.40824829 -0.70360067]
 [-0.80570863  0.40824829  0.42914675]]
[2.69040970e+01 2.02683591e+00 3.19623520e-31]
[[-0.11204534  0.56637371 -0.81649658]
 [-0.58161795 -0.70360067 -0.40824829]
 [-0.80570863  0.42914675  0.40824829]]


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 